### ISSUE TITLE
Call to a member function start() on null on index page

### ISSUE THREAD

**Issue by Albirew** [FlameNET/FlameCMS-2#5]
After a fresh install with latest commit, website index page gives off a blank page and error.log show this:
`PHP Fatal error:  Call to a member function start() on null in system/core/Controller.php on line 70`

**Comment by adomasalcore3** [comment]
ok.... i'll check on that
(remember, that i'm not the one responsable for this repo)

**Comment by adomasalcore3** [comment]
hmmm. do you know that there is no line "70" on the file "system/core/Controller.php"?

**Comment by adomasalcore3** [comment]
i'll commit some corrections, but remember that the "owner" of this repo, isn't "refreshing" the repo. for instance, he nas not updated this repo for ages

**Comment by tlcd96** [comment]
7a4d65ad7cdefd1e987b6616722fcc1c4fe924a6
![image](https://user-images.githubusercontent.com/7103685/27982484-ad3b65f6-6391-11e7-8937-17a72f26c845.png)
account creation is not working for instance...

**Comment by tlcd96** [comment]
if you're watching the flamecms3 repo, that, for instance, is managed by me, but it's not ready yet :(

**Comment by Albirew** [comment]
Yeah, I saw that but by reporting bugs, maybe main dev will wake from his slumber and code again... maybe =)
I also saw flamecms3 but there is still a lot of work to do

As for this issue, I don't know what happened... Maybe sleep deprivation got the best of me and made me mix 2 projects?
Anyway, sorry for that.

**Comment by tlcd96** [comment]
no problem... if you want to know, the installer part of FlameCMS-3 is done
https://github.com/FlameNET/FlameCms-3/commit/8567086912d84aba0be7c97123fed7538f77f539
